---
- hosts: windows
  gather_facts: false
  roles:
    - deploy-elasticsearch-role

# - hosts: windows
#   gather_facts: false
#   roles:
#     - deploy-sql-role

# - hosts: windows
#   gather_facts: false
#   roles:
#     - deploy-iis-role

